apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-iris-workload-prd-hpa
  namespace: default
  labels:
    app: iris-api
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-iris-workload-prd
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 