apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-iris-workload-stg
  namespace: default
  labels:
    app: iris-api
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-api
      environment: staging
  template:
    metadata:
      labels:
        app: iris-api
        environment: staging
    spec:
      containers:
      - name: demo-iris-workload-stg
        image: asia-south2-docker.pkg.dev/mlops-may-2025-iitm/my-repo-stg/iris-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8200
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: iris-api-service-stg
  namespace: default
  labels:
    app: iris-api
    environment: staging
spec:
  selector:
    app: iris-api
    environment: staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8200
  type: LoadBalancer 